const $=id=>document.getElementById(id), num=value=>Number(value||0).toLocaleString('pt-BR'), label=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
let current='dashboard',optionsLoaded=false,uploaded=0;
const uploadSources=[
  ['sap_entry_current','SAP — Entradas','entrada_sisdev.xlsx','Notas de venda com retorno para a unidade comercial.'],
  ['sap_exit_current','SAP — Saídas','saída_sisdev.xlsx','Transferências para a unidade produtora.'],
  ['sap_stock','SAP — Estoque','MB52.xlsx','Saldo por centro, material e lote.'],
  ['sisdev_movement','SISDEV — Movimentações','Relatório de análise de movimentação','Movimentos de entrada e saída do SISDEV.'],
  ['agrotis_recipe','Agrotis — Receitas','ReceitasEmitidas.xls','Receitas emitidas e dados do responsável técnico.']
];
function qs(){return new URLSearchParams({from:$('from').value,to:$('to').value,center:$('center').value,direction:$('direction').value,preferred_rt:$('rt-preference')?.value||''})}
function status(d,name){return d.statuses?.[name]||0}
function renderCharts(d){const values=[['Corretos',status(d,'CORRETO'),'#42c96d'],['Pendentes',status(d,'PENDENTE'),'#e2ab1d'],['Divergentes',status(d,'DIVERGENTE'),'#e44e4a'],['Não lançados',status(d,'NAO_LANCADO'),'#ac62d2']];let at=0,grad=values.map(x=>{let next=at+(d.total?x[1]/d.total*100:0),s=`${x[2]} ${at}% ${next}%`;at=next;return s}).join(',');$('donut').style.background=`conic-gradient(${grad})`;$('legend').innerHTML=values.map(x=>`<li><b style="color:${x[2]}">●</b> ${x[0]} (${num(x[1])})</li>`).join('');const types=d.pending.reduce((a,x)=>{a[x.status]=(a[x.status]||0)+1;return a},{});const max=Math.max(1,...Object.values(types));$('bars').innerHTML=Object.entries(types).map(([k,v])=>`<div><span>${label(k)}</span><i class="bar" style="width:${v/max*100}%"></i><b>${v}</b></div>`).join('')||'<p>Sem divergências no filtro.</p>';}
function render(d){if(!d.ready){$('notice').hidden=false;$('notice').textContent='Envie os arquivos e processe-os para iniciar a auditoria.';return}$('notice').hidden=true;if(!optionsLoaded){$('from').value=d.options.range.min_date||'';$('to').value=d.options.range.max_date||'';$('center').innerHTML='<option value="">Todos os centros</option>'+d.options.centers.map(x=>`<option>${x}</option>`).join('');$('direction').innerHTML='<option value="">Todas</option>'+d.options.directions.map(x=>`<option value="${x.value}">${x.label}</option>`).join('');optionsLoaded=true}setText('total',num(d.total));setText('correct',num(d.correct));setText('correctPct',d.efficacy+'% de eficácia');setText('efficacy',d.efficacy+'%');setText('adherence',d.adherence+'%');setText('adherenceInfo',num(d.launched)+' lançados / '+num(d.total));setText('pending',num(status(d,'PENDENTE')));setText('divergent',num(status(d,'DIVERGENTE')));setText('unposted',num(status(d,'NAO_LANCADO')));setText('donutValue',num(d.total));renderCharts(d);$('issues').innerHTML=d.issues.map(x=>`<p><strong>${x.severity} · ${x.category}</strong><br>${x.message}</p>`).join('')||'<p>Nenhum alerta.</p>';$('table').innerHTML=d.pending.map(x=>`<tr><td>${x.nf}</td><td>${x.doc_date||'—'}</td><td>${x.center||'—'}</td><td>${x.sap_material||'—'}</td><td>${x.manufacturer_lot||'—'}</td><td>${x.quantity??'—'}</td><td>${x.actual_quantity??'—'}</td><td><span class="tag">${label(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="8">Sem pendências no filtro.</td></tr>'}
function setText(id,value){const node=$(id);if(node)node.textContent=value}
function installEfficacyCards(){const efficacyCard=$('efficacy').closest('article');if(!efficacyCard||$('adherence'))return;const card=document.createElement('article');card.className='eff adherence';card.innerHTML='<small>ADERÊNCIA DE LANÇAMENTOS</small><div><strong id="adherence">—</strong><i id="adherenceInfo">Lançados / analisados</i></div>';efficacyCard.after(card);const css=document.createElement('style');css.textContent='.metrics{grid-template-columns:repeat(7,1fr)}.adherence div{background:conic-gradient(#2189d0 0 var(--eff),#24445b var(--eff) 100%)}.adherence{border-color:#2d5a78!important}@media(max-width:1250px){.metrics{grid-template-columns:repeat(4,1fr)}}';document.head.append(css)}
async function load(){const response=await fetch('/api/dashboard?'+qs());render(await response.json())}
function exportButtons(page){let old=$('export-actions');if(old)old.remove();if(page!=='reports')return;let box=document.createElement('div');box.id='export-actions';box.innerHTML='<button>Exportar CSV</button><button>Exportar Excel</button>';let b=box.querySelectorAll('button');b[0].onclick=()=>location.href='/api/export/csv/reports?'+qs();b[1].onclick=()=>location.href='/api/export/xlsx/reports?'+qs();$('page-view').before(box)}
async function showPage(page,nav){current=page;document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$('uploads-view').hidden=page!=='uploads';if(page==='uploads'){$('dashboard-view').hidden=true;$('page-view').hidden=true;$('title').textContent='Importar arquivos';$('subtitle').textContent='Envie as fontes de dados para a conciliação.';exportButtons('');return}if(page==='dashboard'){exportButtons('');$('dashboard-view').hidden=false;$('page-view').hidden=true;$('title').textContent='Dashboard';$('subtitle').textContent='Visão geral da auditoria e conciliação de movimentações de químicos';return load()}const d=await fetch('/api/page/'+page+'?'+qs()).then(r=>r.json());$('dashboard-view').hidden=true;$('page-view').hidden=false;$('title').textContent=nav.textContent.trim();const cols=d.rows.length?Object.keys(d.rows[0]):[];$('page-heading').textContent=nav.textContent.trim();$('page-head').innerHTML='<tr>'+cols.map(c=>`<th>${label(c)}</th>`).join('')+'</tr>';$('page-body').innerHTML=d.rows.map(r=>'<tr>'+cols.map(c=>`<td>${r[c]??'—'}</td>`).join('')+'</tr>').join('')||'<tr><td>Sem registros.</td></tr>';exportButtons(page)}
function buildUploadArea(){$('upload-list').innerHTML=uploadSources.map(([id,title,file,detail])=>`<article class="upload-card"><strong>${title}</strong><small>${detail}<br>Arquivo esperado: ${file}</small><input id="file-${id}" type="file" accept=".xlsx,.xls"><button type="button" data-upload="${id}">Enviar arquivo</button><div id="state-${id}" class="file-state">Aguardando arquivo</div></article>`).join('');document.querySelectorAll('[data-upload]').forEach(button=>button.onclick=()=>uploadFile(button.dataset.upload,button))}
async function uploadFile(source,button){const input=$('file-'+source),state=$('state-'+source),file=input.files[0];if(!file){state.textContent='Selecione uma planilha antes de enviar.';return}if(file.size>50*1024*1024){state.textContent='O arquivo excede o limite de 50 MB.';return}button.disabled=true;state.textContent='Enviando…';try{const form=new FormData();form.append('source',source);form.append('file',file);const response=await fetch('/api/upload',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha no envio.');state.textContent='✓ '+data.file+' enviado com sucesso';state.className='file-state ok';uploaded++;$('upload-status').textContent=`${uploaded} arquivo(s) enviado(s). Pronto para processar.`}catch(error){state.textContent=error.message}finally{button.disabled=false}}
async function processUploads(){const b=$('process-upload');b.disabled=true;b.textContent='Processando…';try{const response=await fetch('/api/import',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível processar os arquivos.');optionsLoaded=false;$('upload-status').textContent='Processamento concluído. '+Object.keys(data.sources||{}).length+' fonte(s) lida(s).';await load()}catch(error){$('upload-status').textContent=error.message}finally{b.disabled=false;b.textContent='Processar arquivos enviados'}}
installEfficacyCards();buildUploadArea();$('apply').onclick=()=>current==='dashboard'?load():showPage(current,document.querySelector('nav a.active'));document.querySelectorAll('nav a[data-page]').forEach(a=>a.onclick=()=>showPage(a.dataset.page,a));$('import').onclick=processUploads;$('process-upload').onclick=processUploads;load();

function installRegularizationNav(){const pending=document.querySelector('nav a[data-page="pending"]');if(!pending)return;const link=document.createElement('a');link.dataset.page='regularization';link.textContent='✓ Regularizar SISDEV';link.onclick=()=>showPage('regularization',link);pending.after(link);const css=document.createElement('style');css.textContent='#page-view{overflow-x:auto}#page-view table{min-width:1100px}#regularization-summary{margin-bottom:12px}';document.head.append(css)}
function exportButtons(page){let old=$('export-actions');if(old)old.remove();if(!['reports','regularization'].includes(page))return;let box=document.createElement('div');box.id='export-actions';box.innerHTML='<button>Exportar CSV</button><button>Exportar Excel</button>';let b=box.querySelectorAll('button');b[0].onclick=()=>location.href='/api/export/csv/'+page+'?'+qs();b[1].onclick=()=>location.href='/api/export/xlsx/'+page+'?'+qs();$('page-view').before(box)}
async function showPage(page,nav){current=page;document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$('uploads-view').hidden=page!=='uploads';if(page==='uploads'){$('dashboard-view').hidden=true;$('page-view').hidden=true;$('title').textContent='Importar arquivos';$('subtitle').textContent='Envie as fontes de dados para a conciliação.';exportButtons('');return}if(page==='dashboard'){exportButtons('');$('dashboard-view').hidden=false;$('page-view').hidden=true;$('title').textContent='Dashboard';$('subtitle').textContent='Visão geral da auditoria e conciliação de movimentações de químicos';return load()}const d=await fetch('/api/page/'+page+'?'+qs()).then(r=>r.json());$('dashboard-view').hidden=true;$('page-view').hidden=false;$('title').textContent=nav.textContent.trim();const cols=d.rows.length?[...new Set(d.rows.flatMap(Object.keys))]:[];$('page-heading').textContent=nav.textContent.trim();$('page-head').innerHTML='<tr>'+cols.map(c=>`<th>${label(c)}</th>`).join('')+'</tr>';$('page-body').innerHTML=d.rows.map(r=>'<tr>'+cols.map(c=>`<td>${r[c]??'—'}</td>`).join('')+'</tr>').join('')||'<tr><td>Sem registros.</td></tr>';let summary=$('regularization-summary');if(summary)summary.remove();if(page==='regularization'&&d.summary){summary=document.createElement('div');summary.id='regularization-summary';summary.className='notice';summary.innerHTML=`<strong>${num(d.summary.total)} notas para regularizar</strong> · ${num(d.summary.entries)} entradas · ${num(d.summary.exits)} saídas · ${num(d.summary.recipes_suggested)} saídas com receita sugerida (D ou D-1).`; $('page-view').before(summary)}exportButtons(page)}
installRegularizationNav();

const baseShowPage=showPage;
showPage=async function(page,nav){await baseShowPage(page,nav);let control=$('rt-preference-control');if(control)control.remove();if(page!=='regularization')return;const settings=await fetch('/api/settings/rt-preference').then(r=>r.json());control=document.createElement('div');control.id='rt-preference-control';control.className='notice';const textNode=document.createElement('strong');textNode.textContent='Qual a preferência de RT? ';const select=document.createElement('select');select.id='rt-preference';for(const value of settings.options||[]){const option=document.createElement('option');option.value=value;option.textContent=value;if(value===settings.preferred_rt)option.selected=true;select.append(option)}control.append(textNode,select);$('page-view').before(control);select.onchange=async()=>{await fetch('/api/settings/rt-preference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferred_rt:select.value})});await showPage('regularization',nav)}};
